### ISSUE TITLE
Mouse courser should indicate that you can tap on the widget

### ISSUE THREAD

**Issue by nilsreichardt** [MingSern/flutter_bounceable#4]
## How it is currently

https://user-images.githubusercontent.com/24459435/169695211-80008c24-a915-4266-a87f-23ed058ce095.mov

## Would I would expect

https://user-images.githubusercontent.com/24459435/169695230-756f106a-c448-4559-9785-7dd6aa81aff1.mov

## Steps to reproduce
1. Run example with web: `flutter run -d chrome`
2. Hover over a card

**Comment by MingSern** [comment]
Thanks for pointing out! This has been added in `v1.0.3`.
